<?php
$this->doctype('XHTML11');
?>
<tr class="plant_property">
    <th>
     <?php
        echo $this->formLabel(
            $this->element->getName(),
            $this->element->getLabel()
        );
        ?>
        <?php if ($this->element->isRequired()) : ?>
            <span class="idl_required_field_star">*</span>
        <?php endif; ?>
    </th>
    <td>
        <?php
        $attributes = $this->element->getAttribs();
        if($this->element->getBelongsTo()){
            $getName = $this->element->getBelongsTo().'['. $this->element->getName().']'; 
        }else{
            $getName = $this->element->getName();
        }
        echo $this->{$this->element->helper}(
            $getName,
            $this->element->getValue(),
            $attributes
        );
        echo ' ' . $this->element->getAttrib('custom');
        ?>
    </td>
    <td class="error">
        <?php if ($this->element->getMessages()) : ?>
        <?php
        $message = $this->element->getMessages();
        $message = reset($message);
        ?>
        <div class="idl_error_wrapper">
            <div class="idl_error_icon"></div>
            <div class="idl_error_message">
                <?php echo $message; ?>
            </div>
        </div>
        <?php endif; ?>
    </td>
</tr>
