<?php
$this->doctype('XHTML11');
if ($this->dependencies != null) {
    $depScripts = "";
    $dependency_nodes = $this->dependencies->getElementsByTagName('dependency');
    foreach ($dependency_nodes as $dependency_node) {
        $parent_name = $dependency_node->getAttribute('element');
        $values_nodes = $dependency_node->getElementsByTagName('value');
        foreach ($values_nodes as $value_node) {
            $depScripts .= 'if (typeof dependencies["' . $parent_name . '"] == "undefined") {
                dependencies["' . $parent_name . '"] = [];
            }
            if (typeof dependencies["' . $parent_name . '"]["v_' . $value_node->nodeValue . '"] == "undefined") {
                dependencies["' . $parent_name . '"]["v_' . $value_node->nodeValue . '"] = [];
            }
            dependencies["' . $parent_name . '"]["v_' . $value_node->nodeValue . '"].push("' . $this->element->getName() . '");';
        }
    }
    $this->headScript()->appendScript($depScripts);
}
?>
<?php $group_label_input = isset($this->group_label_input) && $this->group_label_input; ?>
<?php if (!$group_label_input || (!isset($this->start) || $this->start)) : ?>
<tr>
<?php endif; ?>
    <?php if (!$group_label_input) : ?>
        <th>
    <?php else : ?>
        <?php if ((!isset($this->start) || $this->start) && (!isset($this->end) || $this->end)) : ?>
        <td class="element" colspan="3">
        <?php else : ?>
        <td class="element">
        <?php endif; ?>
    <?php endif; ?>
        <?php echo $this->formLabel(
            $this->element->getName(),
            $this->element->getLabel()
        ); ?>
        <?php if ($this->element->getDescription()) : ?>
            <span class="comment">
                <?php echo $this->element->getDescription(); ?>
            </span>
        <?php endif; ?>
        <?php if ($this->element->isRequired()) : ?>
            <span class="idl_required_field_star">*</span>
        <?php endif; ?>
    <?php if (!$group_label_input) : ?>
    </th>
    <td>
    <?php endif; ?>
        <ul class="idl_inline_list">
            <li>
            <?php
            $classArray = array(
                'class' => '',
                'onchange' => $this->element->onchange
            );
            if ($this->element->disable == 'disable') {
                $classArray['disable'] = $this->element->disable;
            }
            echo $this->{$this->element->helper}(
                $this->element->getName(),
                $this->element->getValue(),
                $classArray,
                $this->element->getMultiOptions(),
                "</li>\n<li>"
            );
            ?>
            </li>
        </ul>
    </td>
    <td class="error">
        <?php if ($this->element->getMessages()) : ?>
        <?php
        $message = $this->element->getMessages();
        $message = reset($message);
        ?>
        <div class="idl_error_wrapper">
            <div class="idl_error_icon"></div>
            <div class="idl_error_message">
                <?php echo $message; ?>
            </div>
        </div>
        <?php endif; ?>
    </td>
<?php if (!$group_label_input || (!isset($this->end) || $this->end)) : ?>
</tr>
<?php endif; ?>
