<?php
$this->doctype('XHTML11');
if ($this->dependencies != null) {
    $depScripts = "";
    $dependency_nodes = $this->dependencies->getElementsByTagName('dependency');
    foreach ($dependency_nodes as $dependency_node) {
        $parent_name = $dependency_node->getAttribute('element');
        $values_nodes = $dependency_node->getElementsByTagName('value');
        foreach ($values_nodes as $value_node) {
            $depScripts .= 'if (typeof dependencies["' . $parent_name . '"] == "undefined") {
                dependencies["' . $parent_name . '"] = [];
            }
            if (typeof dependencies["' . $parent_name . '"]["v_' . $value_node->nodeValue . '"] == "undefined") {
                dependencies["' . $parent_name . '"]["v_' . $value_node->nodeValue . '"] = [];
            }
            dependencies["' . $parent_name . '"]["v_' . $value_node->nodeValue . '"].push("' . $this->element->getName() . '");';
        }
    }
    $this->headScript()->appendScript($depScripts);
}
?>
<?php $group_label_input = isset($this->group_label_input) && $this->group_label_input; ?>
<?php if (!$group_label_input || (!isset($this->start) || $this->start)) : ?>
<tr>
<?php endif; ?>
    <td>
        <?php
        echo $this->formLabel(
            $this->element->getName(),
            $this->element->getLabel() . ($this->element->isRequired() ? ' *' : '')
        );
        ?>
        <?php if ($this->element->getDescription()) : ?>
            <span class="comment">
                <?php echo $this->element->getDescription(); ?>
            </span>
        <?php endif; ?>
        <ul>
            <li>
            <?php
            echo $this->{$this->element->helper}(
                $this->element->getName(),
                $this->element->getValue(),
                $this->element->getAttribs(),
                $this->element->getMultiOptions(),
                "</li>\n<li>"
            );
            ?>
            </li>
        </ul>
    </td>
    <td class="field_error">
        <?php if ($this->element->getMessages()) : ?>
        <?php
        $message = $this->element->getMessages();
        $message = reset($message);
        ?>
        <div class="field_error_wrapper">
            <div class="field_error_icon"></div>
            <div class="field_error_message">
                <?php echo $message; ?>
            </div>
        </div>
        <?php endif; ?>
    </td>
<?php if (!$group_label_input || (!isset($this->end) || $this->end)) : ?>
</tr>
<?php endif; ?>
