<?php $this->doctype('XHTML11'); ?>
<tr>
    <th>
        <?php
        echo $this->formLabel(
            $this->element->getName(),
            $this->element->getLabel()
        );
        ?>
        <?php if ($this->element->isRequired()) : ?>
            <span class="idl_required_field_star">*</span>
        <?php endif; ?>
    </th>
    <td>
        <?php
        $attribs = $this->element->getAttribs();
        unset($attribs['helper']);
        echo $this->{$this->element->helper}(
            $this->element->getName(),
            $this->element->getValue(),
            $attribs,
            $this->element->options
        );
        echo ' ' . $this->element->getAttrib('custom')
        ?>
    </td>
    <td class="field_error">
        <?php if ($this->element->getMessages()) : ?>
        <?php
        $message = $this->element->getMessages();
        $message = reset($message);
        ?>
        <div class="field_error_wrapper">
            <div class="field_error_icon"></div>
            <div class="field_error_message">
                <?php echo $message; ?>
            </div>
        </div>
        <?php endif; ?>
    </td>
</tr>
