<h1>Liste des propriétés de style des éléments de la carte</h1>
<table class="table table-bordered table-striped">
    <thead>
        <tr>    
            <th>Nom</th>
            <th>Type / Valeurs possibles</th>
            <th>Description</th>
        </tr>
    </thead>
    <tbody>
        <tr><td>stroke</td><td> String, Code hexadécimal</td><td> couleur de trait</td></tr>
        <tr><td>stroke-dasharray</td><td> "", "-", ".", "-.", "-..", ". ", "- ", "--", "- .", "--.", "--.."</td><td> type de trait</td></tr>
        <tr><td>stroke-linecap</td><td>"butt", "square", "round"</td><td></td></tr>
        <tr><td>stroke-linecap</td><td>"bevel", "round", "miter"</td><td></td></tr>
        <tr><td>stroke-opacity</td><td> float</td><td>opacité du trait de 0 à 1</td></tr>
        <tr><td>stroke-width</td><td> int</td><td>largeur du trait en pixel, par défaut, 1</td></tr>
        <tr><td>fill</td><td> String, Code hexadécimal</td><td> couleur de remplissage de la zone</td></tr>
        <tr><td>opacity</td><td> float</td><td> opacité de la zone de 0 à 1</td></tr> 
    </tbody>
</table>
