
<script type="text/javascript">


        $(document).ready(function() {


            var map = new Pam.Map.DomMap($(".map-content"), Pam.map);

        });
</script>

<!-- Main hero unit for a primary marketing message or call to action -->
<div class="hero-unit">
  <div class="map-content">
    <div data-name="Chartres"> Hello ! </div>
    <div data-name="Chinon"> chinon ! </div>
    <div data-name="Le Mans"> Le Mans ! </div>
  </div>
  <h1 class="home">Votre carte interactive</h1>
  <p>Intégrez sur votre site Web une carte vectorielle facile à installer, hautement paramétrable et pensée pour le référencement naturel.  </p>
  <p><a class="btn btn-primary btn-large">En savoir plus...</a></p>
  <div class="clear"></div>
</div>
<!-- Example row of columns -->
<div class="row">
  <div class="span4">
    <h2>Facile à installer</h2>
    <p>Les cartes interactives de <?php echo $this->config->brand_name ?> s'installent en à peine 2 minutes. Il vous suffit d'inclure un fichier javascript et de placer une balise HTML à l'endroit ou vous souhaitez placer la carte</p>
    <p><a class="btn" href="#">En savoir plus &raquo;</a></p>
  </div>
  <div class="span4">
    <h2>Paramétrable</h2>
    <p>Vous pouvez paramétrer votre carte comme bon vous semble : modifier de nombreux attributs CSS de la carte, comme la couleur de fond, l'épaisseur du trait, et de nombreux effets au passage de la souris.</p>
    <p><a class="btn" href="#">En savoir plus &raquo;</a></p>
 </div>
  <div class="span4">
    <h2>SEO Friendly</h2>
    <p>Les cartes <?php echo $this->config->brand_name ?> s'adaptent parfaitement à votre stratégie de netlinking interne vers les pages de localités. Bénéficiez de l'expertise en référencement naturel des cartes <?php echo $this->config->brand_name; ?>...</p>
    <p><a class="btn" href="#">En savoir plus  &raquo;</a></p>
  </div>
</div>
