<h2><?php echo $this->message; ?></h2>
<?php if (isset($this->exception)) : ?>
	<h3>Exception information:</h3>
	<p>
		<strong>Type :</b> <?php echo get_class($this->exception); ?></strong><br />
		<strong>Message :</b> <?php echo $this->exception->getMessage(); ?></strong>
	</p>
	
	<h3>Stack trace:</h3>
	<pre><?php echo $this->exception->getTraceAsString(); ?></pre>
	
	<h3>Request Parameters:</h3>
	<pre><?php echo var_export($this->request->getParams(), true); ?></pre>
<?php endif; ?>
