<div class="navbar navbar-inverse navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
      <a class="brand logo" href="/" title="Carte Interactive"><img src="/img/front/map_logo.png" alt="Carte Interactive"/><?php echo $this->config->brand_name ?></a>
      <div class="nav-collapse collapse">
        <ul class="nav">
          <li class="dropdown">
            <span class="link dropdown-toggle" data-toggle="dropdown">Produit <b class="caret"></b></span>
            <ul class="dropdown-menu">
              <li><a href="/map/carte-1">Carte du monde</a></li>
              <li><a href="/map/carte-1">Carte d'Europe</a></li>
              <li><a href="/map/carte-1">Carte de France</a></li>
              <li><a href="/map/carte-1">Carte des régions</a></li>
              <li><a href="/map/carte-1">Carte des départements</a></li>
            </ul>
          </li>
          <li><a href="docs">Documentation</a></li>
          <li><a href="/docs/pricing">Pricing</a></li>
        </ul>
      </div>
    </div>
  </div>
</div>

