<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
	<?php echo $this->headTitle(); ?>
    <link rel="icon" type="image/png" href="/img/front/map_black.png">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
	<script src="/js/jquery-last.min.js"></script>
	<script src="/js/prettify.js"></script>
	<script src="/js/bootstrap.min.js"></script>
    <script src="/pam_debug.js"></script>
    <script src="/map_france_1_3_400x400.js"></script>
    <?php echo $this->headScript();?>
    <script>
        $(function() {
            prettyPrint();
        });
    </script>
    <link href="/mapnager/js/mapnager.css" rel="stylesheet">
    <link href="/css/bootstrap.min.css" rel="stylesheet">
    <link href="/css/prettify.css" rel="stylesheet">
    <link href="/css/front.css" rel="stylesheet">
    <?php echo $this->headLink();?>
  </head>

  <body>
    <?php echo $this->partial('/partial/nav.phtml', array('config'=>$this->config)); ?>
    <div class="container <?php echo $this->controller; ?>">
        <?php echo $this->layout()->content; ?>
        <hr>
        <footer>
            <p>&copy; Vamboisset Media</p>
        </footer>

    </div> <!-- /container -->
  </body>
</html>

